version: '3'
services:
  app:
    container_name: nextcloud-app
    image: nextcloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    environment:
      - POSTGRES_HOST=192.168.1.13
      - POSTGRES_DB_FILE=nxcld
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_ADMIN_PASSWORD=p@$$w0rd
      - NEXTCLOUD_ADMIN_USER=admin
    volumes:
      - ./app_data:/var/www/html
  onlyoffice-document-server:
    container_name: onlyoffice-app
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
  nginx:
    container_name: cloud-nginx
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 1180:80
      - 1443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:rw
      - ./app_data:/var/www/html